spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    username: payment
    password: payment123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  flyway:
    enabled: false

server:
  port: 8081

bank:
  service:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.bank.payment: DEBUG
